### PR TITLE
Update publish-to-anaconda.yml

### PR DESCRIPTION
**Pull request by scottcoughlin2014**

### CODE REVIEW

**Comment by astroJeff** [comment]
Update (Feb 8): Waiting on Scotty to fix conda build, resolving all the dependencies

**Comment by astroJeff** [comment]
Update (Feb 15): No updates. @maxbriel to e-mail Scotty again (cc'ing me)

**Comment by astroJeff** [comment]
Update (Feb 22): Still waiting on Scotty. @maxbriel and others will work on offline.

**Comment by mkruckow** [comment]
Update (Feb 29): Still waiting on Scotty.

**Pull request closed without merging**
