### PR TITLE
update installation test to include M1 and intel chips for macos

### PR DESCRIPTION
**Pull request by elizabethteng**
add macos-14 github runner which uses the apple silicon M1 chip: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

### CODE REVIEW

**Comment by elizabethteng** [comment]
info about github runners [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

**Comment by elizabethteng** [comment]
may want to discuss github billing for extra minutes: https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates

**Comment by maxbriel** [comment]
Can we change this to `macos-13` and `macos-latest`?
Latest is already on the M1 chipset, `macos-13` allows testing on a x86 (intel) chipset. And this means we won't have to update it when new OS releases come out :)

**Comment by elizabethteng** [comment]
good idea Max! I guess I had left open the possibility that later mac setups could go back to intel but now that I'm actually thinking about it it's unlikely to happen.

**Review by maxbriel — APPROVED** [review]
Great! Approved :)

**Review by mkruckow — APPROVED** [review]

**Pull request merged**
