### PR TITLE
Update V1 conda setup

### PR DESCRIPTION
**Pull request by maxbriel**
This PR should update the conda setup for POSYDON to make sure v1 is correctly installed.
Currently, the conda version is not up-to-date with the github v1 version. This is mostly problematic for the dependencies.

To-do:
[x] update conda/meta.yaml
[ ] build conda packages
[ ] migrate the anaconda github action upload to the POSYDON repository?

### CODE REVIEW

**Comment by mkruckow** [comment]
Could you please comment on the remaining differences?

module                |conda/meta.yaml|setup.py
----------------------|---------------|--------
astropy               |4.0.1.post1    |4.0.1
matplotlib-label-lines|0.5.1          |0.3.8
PyQt5                 |?              |5.15.3
pytables vs. tables

In case there if there are things missing on conda, could/should we consider to update the versions in `setup.py`?

**Comment by maxbriel** [comment]
The `pytables` vs `tables` is a naming difference for the same package between different repos. They are the same package, but named differently.

pyqt5 can be added in conda, but not `5.15.3`. `5.15.10` still supports python 3.7 according to pypi. However, this is not the actual supported version. It requires 3.11. 

For `astropy`, `4.0.1` is not available on conda. Only this `4.0.1.post1` version. I picked the closest version to setup.py. Unclear if they're completely the same. We can change `setup.py` to `4.0.1.post1`.

For `matplotlib-label-lines`, I picked the latest for 3.7 on conda. `0.3.8` is not on conda. We can update `setup.py` to match

**Comment by maxbriel** [comment]
PyQt5 is available on conda with version `5.15.4`

**Comment by astroJeff** [comment]
Status update (Dec 14): The documentation changes are all correct. We will accept, which should test the GitHub action to update the Conda install.

**Review by astroJeff — APPROVED** [review]

**Review by mkruckow — APPROVED** [review]

**Comment by astroJeff** [comment]
Push to Conda (github action) failed - something related to python wheels. @maxbriel to update.

**Pull request merged**
