### PR TITLE
Inhomogeneous binary array

### PR DESCRIPTION
**Pull request by ezapartas**

### CODE REVIEW

**Comment by ezapartas** [comment]
trying to generally solve both inhomogeneity of singlestar array and solve the specific issue was occurring for track_interpolation and intial_RLO #235

**Comment by maxbriel** [comment]
This works for me on the test binary I found for Issue #235. However, I've not tested this in a population run.

**Comment by astroJeff** [comment]
Update (Feb 8): PR appears to address issue #235 dealing with inhomogeneous arrays. It has been tested for individual problematic binaries but needs to be tested on a population. @dimsour94 to run a population and update.

**Comment by astroJeff** [comment]
A question was raised about the use of `["NAN"]` as a placeholder. We should try changing this to `[np.nan]`. @dimsour94 to test this, to see if other issues arise in making this change.

**Review by maxbriel — APPROVED** [review]

**Comment by dimsour94** [comment]
Feb 13/02/2024:

["NAN"] changed to [np.nan]+tested in a population run of 10000 binaries with track interpolation and works fine. I think it's ready to be accepted.

**Review by dimsour94 — APPROVED** [review]

**Pull request merged**
