### PR TITLE
Copy column list for MESA

### PR DESCRIPTION
**Pull request by mkruckow**
This PR addresses issue #47.

- [x] Copy column list into work directory and use them for the runs.
- [x] Add waits on git checkout.
- [x] testing

### CODE REVIEW

**Comment by astroJeff** [comment]
We briefly discussed this PR. @mkruckow has tested this, but we want @sgossage to test it before accepting.

**Comment by astroJeff** [comment]
Update (Jan 18): We discussed this PR briefly, but we want Seth to test before accepting

**Comment by sgossage** [comment]
I've tested this PR and it does solve issue #47. I think it is ready to merge.

I remember that there may be a related niche issue to consider though when running grids using various branches of `POSYDON-MESA-INLISTS`. Currently when `posydon-setup-grid` tries to clone the inlist submodule to the home directory, it first checks if `.posydon_mesa_inlists` already exists there and will not clone the inlist submodule if it does exist. So, if you run one grid using an inlist submodule from `branch_x` and then try running another with `branch_y`, you have to remember to delete `.posydon_mesa_inlists` in your home directory in order to clone the inlist submodule of `branch_y` (or make local edits to inlist files).

I'm not sure if it would be worth disabling the check to only download clone the inlists submodule if it doesn't exist, but wanted to bring this up in case people think it may be worthwhile to change.

**Comment by mkruckow** [comment]
Yes, there is this issue, that sometimes the old instead of the new branch is used.
But I think, this is not related to not be cloned. The code only clones the repo if non is there. This is correct in terms of efficiency. In any case the new branch is checked out and pulled  Hence, it should get updated. But I think, often the code proceeds further, before the git actions are completed on disk. Thus, it uses old data from disk for the copy.
Why I think it is the case that the git actions are simply delayed instead of not performed, like @sgossage suggested: if you do the `posydon-setup-grid` twice, it will usually have the new version, because till than the first git actions are completed on disk. For a prove, after the update to the new branch didn't work, check the current branch in `.posydon_mesa_inlists` by hand. If @sgossage is correct, it will have the old branch, if I'm correct it will show you the desired branch.

**Comment by mkruckow** [comment]
@kkovlakas , would you think that it would be sufficient to add a `proc.wait()` in line 144 or would we need this several times for each call of the subprocess module?

**Comment by astroJeff** [comment]
Update (Jan 25): There is an issue listed above about adding a wait statement to make sure the subprocess has completed before moving on. @mkruckow to test.

**Comment by mkruckow** [comment]
OK, I have inserted three waits. On made the code fail, has I removed this again. Now it runs through.
As I can't enforce a problematic situation, where the file system is slow on writing, I can't test it further.

If anybody has an idea who to ensure a more detailed test, please do so!
Otherwise, @sgossage , @astroJeff , @kkovlakas please do a final review of this PR.

**Review by kkovlakas — APPROVED** [review]

**Review by astroJeff — APPROVED** [review]

**Pull request merged**
