### PR TITLE
Vhd multiple to development

### PR DESCRIPTION
**Pull request by WeneKouarfate**
@ssbvr is it OK?

### CODE REVIEW

**Comment by ssbvr** [comment]
Yes, as soon as I have a moment next week I will review the PR!

**Review by ezapartas — DISMISSED** [review]

**Comment by ssbvr** [comment]
Hi @WeneKouarfate I tested the code and get the following error, any idea what's going on here? 
```bash
TypeError                                 Traceback (most recent call last)
File /posydon/visualization/VH_diagram/GraphVisualizer.py:506, in GraphVisualizerState.paintEvent(self, event)
    500 x_S2 = (
    501     self._bg.width() [/](https://file+.vscode-resource.vscode-cdn.net/) 2
    502     + (self._bg.width() [/](https://file+.vscode-resource.vscode-cdn.net/) 2 - self._S2_pixmap.width()) * self._distance
    503 )
    504 y_S2 = self._bg.height() [/](https://file+.vscode-resource.vscode-cdn.net/) 2 - self._S2_pixmap.height() [/](https://file+.vscode-resource.vscode-cdn.net/) 2
--> 506 painter.drawPixmap(x_S2, y_S2, self._S2_pixmap)
    508 if not self._event_pixmap.isNull():
    509     x_event = self._bg.width() [/](https://file+.vscode-resource.vscode-cdn.net/) 2 - self._event_pixmap.width() [/](https://file+.vscode-resource.vscode-cdn.net/) 2

TypeError: arguments did not match any overloaded call:
  drawPixmap(self, targetRect: QRectF, pixmap: QPixmap, sourceRect: QRectF): argument 1 has unexpected type 'numpy.float64'
  drawPixmap(self, targetRect: QRect, pixmap: QPixmap, sourceRect: QRect): argument 1 has unexpected type 'numpy.float64'
  drawPixmap(self, p: Union[QPointF, QPoint], pm: QPixmap): argument 1 has unexpected type 'numpy.float64'
  drawPixmap(self, p: QPoint, pm: QPixmap): argument 1 has unexpected type 'numpy.float64'
  drawPixmap(self, r: QRect, pm: QPixmap): argument 1 has unexpected type 'numpy.float64'
  drawPixmap(self, x: int, y: int, pm: QPixmap): argument 1 has unexpected type 'numpy.float64'
  drawPixmap(self, x: int, y: int, w: int, h: int, pm: QPixmap): argument 1 has unexpected type 'numpy.float64'
  drawPixmap(self, x: int, y: int, w: int, h: int, pm: QPixmap, sx: int, sy: int, sw: int, sh: int): argument 1 has unexpected type 'numpy.float64'
  drawPixmap(self, x: int, y: int, pm: QPixmap, sx: int, sy: int, sw: int, sh: int): argument 1 has unexpected type 'numpy.float64'
  drawPixmap(self, p: Union[QPointF, QPoint], pm: QPixmap, sr: QRectF): argument 1 has unexpected type 'numpy.float64'
  drawPixmap(self, p: QPoint, pm: QPixmap, sr: QRect): argument 1 has unexpected type 'numpy.float64'
```

**Comment by ssbvr** [comment]
The development branch is also broken. I think I know what's going on. A few month ago we made the switch to python 3.11 and updated all modules, however we never updated the VDH plotting library to work on the newer version of PyQt5. The code needs to be vetted to work on the latest version of PyQt5 on Python 3.11.

**Comment by WeneKouarfate** [comment]
Yes we had this problem during our last meeting and I may have commit the casting into int on line 506 and 511 as I did at 498 on the wrong pc. As I am also working on my side on a possible intégration of the single, multiple and hierarchical plot in one function call and improving the _remove_duplicate method it could be usefull to know in more precisely the occurence of the error to try it after review as I haven't seen this error since a while.

**Comment by ssbvr** [comment]
> Yes we had this problem during our last meeting and I may have commit the casting into int on line 506 and 511 as I did at 498 on the wrong pc. As I am also working on my side on a possible intégration of the single, multiple and hierarchical plot in one function call and improving the _remove_duplicate method it could be usefull to know in more precisely the occurence of the error to try it after review as I haven't seen this error since a while.

Hi @WeneKouarfate, thank you for the quick follow-up. I emailed you the notebook with the error which is a straight copy from your tutorial. To reproduce the error, create a new Python environment with python=3.11 and run the code.

**Pull request closed without merging**
