### PR TITLE
Synthetic Population Restructure

### PR DESCRIPTION
**Pull request by maxbriel**
This address a few issues with the Synthetic Population class I ran into while selecting and analysis a different (specifically larger) population than the BBH population. Due to the fundamental changes in processing due to keeping part of the processing on-disk, this touches large parts of the syntheticpopulation file.

Goals of the PR:
- Separate the current SyntheticPopulation into separate classes based on the specific task, i.e. running a population, parsing a population, and calculating transient rates. This will allow for easier future growth of this component.
- Perform on-disk selection to decrease the RAM usage footprint.

To-Do:
Each step combines separation and moving processing to on-disk storage.
- [x] PopulationRunner [Manages a population run and merges separate runs into a file per metallicity]
- [x] ParsedPopulation [used to parse a population given a specific binary state]
     - [x] initial parsing of the population from different metallicities.
     - [x] calculate the formation channels of binaries
     - [x] creation of SyntheticPopulation
          - [x] DCO
          - [x] GRBs
- [x] SyntheticPopulation [on-disk dataframe to store an event per row with specified properties of the binary]
    - [x] metallicity efficiency
    - [x] delay time calculation
    - [x] calculate intrinsic population with given MODEL
- [x] Rates
   - [x] event rate over redshift and other properties.
- [x] SampledPopulation
    - [x] Account for different detector efficiency
    - [x] Different synthetic population types

- [x] 'On-disk' rate calculations using the current `Rates` class 

- [x] Plotting routines

- [x] Additional abstraction of the synthetic population creation.

### CODE REVIEW

**Comment by astroJeff** [comment]
Status Update (Dec 14): Not ready yet (still in draft stage). Tutorials still need updating. Need some plotting functionality. A couple people can start working on this and testing it (and help out with tutorials). @dimsour94 @kkovlakas

**Comment by astroJeff** [comment]
Update (Jan 25): We discussed the issue of population parsing. It will be addressed in a separate, future PR, once we resolve our ideal architecture. Still need tutorials and additional plotting functionality. @maxbriel to finish up - let's revisit next week. @ezapartas to test.

**Comment by maxbriel** [comment]
This PR is basically finished. However, it is quite a restructure of the classes and the data associated with it, so requires some serious testing.

I think we should have a further discussion about how we process the data and how we manage data. If the approach implemented in this PR is the way to go, we should adjust the tutorials accordingly.

Main changes:
1. All data is held in a single instead of in-memory. As such, each class has a file associated with it, which is read or created when a class instance is created.
2. Population runs and analysis/post-processing has been split up into different classes.
3. The pipeline of population runs -> ParsedPopulation -> SyntheticPopulation -> Rates -> Sampled Population is still present, but is split in different classes.
4. Abstraction in creating SyntheticPopulation with the `create_synpop` function from a ParsedPopulation.
5. All calculations up to `plot_over_grid_slice`, but not including, are done in chunks. The plotting can be further rewritten to allow for chunking too.

There are some considerations to make on how we're handling the Rates calculation (convolution with the SFR + metallicity evolution). Currently, these are still very split between different types ('DCO', "GRB"). And I had to code in some selection identifiers to determine which one is calculated. However, for the most part the Intrinsic rates calculations can be abstracted; once observational effects play a role, it becomes more difficult to generalize them.

**Comment by astroJeff** [comment]
Update (Feb 8): This PR seems ready to go, but we want more discussion to ensure this is the "best" way to implement population generation. @ka-rocha @dimsour94 @ezapartas to discuss offline.

**Comment by astroJeff** [comment]
Update (Feb 15): @maxbriel met offline with others, and there are a few small specific things to be updated and cleaned. PR should be ready in a week or two.

**Comment by astroJeff** [comment]
Update (Feb 22): From Max: one more week needed to finalize this PR.

**Comment by mkruckow** [comment]
Update (Feb 29): It is nearly finished. Max gave an introduction, who to use the new functionalities.

**Comment by maxbriel** [comment]
I've closed this PR, since it's superseded by PR  #267 , which implements the analysis framework in a cleaner way.

**Pull request closed without merging**
