### PR TITLE
update v1 for scikit-learn version

### PR DESCRIPTION
**Pull request by elizabethteng**
resolving incompatibility between v1 syntax and current sklearn dependency

### CODE REVIEW

**Comment by elizabethteng** [comment]
tried changing from existing v1 [environment](https://github.com/POSYDON-code/POSYDON/pull/266) to have sklearn 0.21.3 to resolve incompatibility. Now getting issues with incompatibility of code with numpy>1.20

**Comment by elizabethteng** [comment]
on my laptop with M3 chip: updated to numpy=1.19.0, now getting error related to libtiff
Screenshot 2024-04-24 at 13 02 57

**Comment by elizabethteng** [comment]
Tried again with QUEST, post-conda install downgrading to sklearn 0.21.3 and numpy 1.19.0. Tutorial seems to run okay. I'll add that the tutorial, when referencing "PATH_TO_POSYDON_DATA", is expecting the data to be in a directory in that path called "POSYDON_data", which is not the case for the new file structure on QUEST.

**Comment by elizabethteng** [comment]
tried installing this branch on QUEST from scratch with changes to numpy and sklearn requirements. Installation worked and running populations tutorial worked.

**Comment by elizabethteng** [comment]
installed from scratch github clone. installation worked, got following error when trying "run populations" tutorial. 

Screenshot 2024-04-24 at 14 18 08

**Comment by astroJeff** [comment]
Update (Apr 25): @elizabethteng to try and resolve minimum column size error listed above. To discuss with @ka-rocha and @celiotine

**Comment by elizabethteng** [comment]
unable to reproduce error -- everything working fine now. May have been running on the wrong environment in the previous error.

**Review by astroJeff — APPROVED** [review]

**Review by celiotine — APPROVED** [review]

**Pull request merged**
